### ISSUE TITLE
Conda packaging problems

### ISSUE THREAD

**Issue by johnwason** [robotraconteur-contrib/robotraconteur_training_sim#5]
@Tobias-Fischer @traversaro

This is the feedstock of the package I am trying to get to work. It depends on some of the other packages in the `robotraconteur` and `wasontech` conda channels. I am going nuts trying to get the conda packages working, I keep running into bizarre behavior and version mismatches on Windows and Linux. I am having similar problems with the tesseract packages.

**Comment by johnwason** [comment]
See also https://github.com/tesseract-robotics/tesseract/pull/930 . This is my attempt to add in a CI test so we don't have to patch for conda specifically. The errors here are not with conda, they are with my patch.

**Comment by traversaro** [comment]
What are the errors you are referencing to?

**Comment by johnwason** [comment]
On Linux, it is the version mismatch problems discussed in https://github.com/conda-forge/gazebo-feedstock/issues/183 . On Windows I am having a problem where gazebo will either fail to start or sometimes the user interface will hang on open and require a force quit. I haven't been able to find a consistent reason for either behavior. It seems some of the builds of gazebo are also broken in some way.

The feedstocks for the packages I am working on can be found here:

* https://github.com/robotraconteur-packaging/robotraconteur-feedstock
* https://github.com/robotraconteur-packaging/robotraconteur_companion-feedstock
* https://github.com/robotraconteur-packaging/gazebo_robotraconteur_server_plugin-feedstock
* https://github.com/robotraconteur-packaging/robotraconteur_companion_python-feedstock
* https://github.com/robotraconteur-packaging/gazebo-robotraconteur-sim-drivers-feedstock
* https://github.com/robotraconteur-packaging/robotraconteur_training_sim-feedstock
* https://github.com/johnwason/drekar-launch-feedstock
* https://github.com/johnwason/drekar-launch-process-feedstock
* https://github.com/johnwason/drekar-launch-process-cpp-feedstock
* https://github.com/johnwason/tesseract-robotics-superpack-feedstock (this one is out of date currently)

You guys may also find drekar-launch interesting. It works really well with the training simulator to launch and manage all the programs in a conda environment. Here is an example of the launch configuration for the training simulator: https://github.com/robotraconteur-contrib/robotraconteur_training_sim/blob/v0.3.0_dev/gz_example/2ur5e/drekar-launch.yaml.j2

**Comment by Tobias-Fischer** [comment]
Regarding Gazebo: We know that old builds are broken - please make sure to pull in the latest build. If, like on Linux, there are some packages that are not compatible with the latest gazebo build, we can fix this up.

If you could check if you encounter these issues with the latest build of gazebo as well, that'd be great.

PS: Looking forward to having all those feedstocks on conda-forge, looks like there's very cool stuff in there :)

**Comment by johnwason** [comment]
The new versions of conda seem to have fixed the issues I was having. Closing for now.
