### ISSUE TITLE
Problems Adapting ur5_client_*.py files for Hardware 

### ISSUE THREAD

**Issue by nrsprs** [robotraconteur-contrib/robotraconteur_training_sim#6]
Hi,

I'm trying to use the training motion command files in the example_scripts directory on my UR10e, but I am receiving the error: RobotRaconteur.RobotRaconteurPythonError.ConnectionException: RobotRaconteur.ConnectionError Could not connect to service 

when I run the script.

I have my robot on port 192.168.1.102, and am connecting to port 30004 with the 'robot' service. Here's my Connect Service command:
c=RRN.ConnectService('rr+tcp//192.168.1.1.102:30004?service=robot')

Am I attempting to connect to the wrong port? Is there something that I'm missing?  Thank you.

**Comment by johnwason** [comment]
> rr+tcp//192.168.1.1.102:30004?service=robot

It looks like you have an extra "1" in the IP address.

Are you running the RR driver for UR? The UR does not support Robot Raconteur without the driver.

https://github.com/robotraconteur-contrib/URRobotRaconteurDriver
